// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVb7B1kSsBjWD3lPvMBZ91BVVjTufGaLg',
    appId: '1:849919976521:web:f3cddefbba41c2fddb4b98',
    messagingSenderId: '849919976521',
    projectId: 'login-930b7',
    authDomain: 'login-930b7.firebaseapp.com',
    storageBucket: 'login-930b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzlVrpfP-oDCfBaNu4HaUGAh5A2RBlg-I',
    appId: '1:849919976521:android:db456540fa22d451db4b98',
    messagingSenderId: '849919976521',
    projectId: 'login-930b7',
    storageBucket: 'login-930b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr4Zn9B9h4x4RsUKGXi-dQpGit5UsnwpE',
    appId: '1:849919976521:ios:8549cff018193161db4b98',
    messagingSenderId: '849919976521',
    projectId: 'login-930b7',
    storageBucket: 'login-930b7.appspot.com',
    iosClientId: '849919976521-dbakufom7li50jnr7fgi77dvk0mcaorh.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
